rpc:
  name: my-rpc
  version: 2.0
  mock: false
  serializer: kryo
  loadBalancer: roundRobin
  retryStrategy: fixedInterval
  tolerantStrategy: failFast
  registryConfig:
    registry: etcd
    address: http://localhost:2379